theme: jekyll-theme-minimal

title: Jeongsoo Kim
# logo: /profile.jpg
description: >
  Independent Researcher<br>
  M.S. in Artificial Intelligence<br>
  (Sogang University)<br>
  <br>
  📍 Hiroshima, Japan<br>
  ✉️ jskim1@sogang.ac.kr
